"""Initial migration

Revision ID: 31654492ed3d
Revises: 
Create Date: 2026-02-11 20:56:06.832600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31654492ed3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    op.create_table('trivias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trivias'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('participations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trivia_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'finished', name='participationstatus', native_enum=False), nullable=False),
    sa.Column('score_total', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trivia_id'], ['trivias.id'], name=op.f('fk_participations_trivia_id_trivias')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_participations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participations')),
    sa.UniqueConstraint('trivia_id', 'user_id', name='uq_participation_trivia_user')
    )
    op.create_index('ix_participations_trivia_id', 'participations', ['trivia_id'], unique=False)
    op.create_index('ix_participations_user_id', 'participations', ['user_id'], unique=False)
    op.create_table('question_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_question_options_question_id_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_options'))
    )
    op.create_index('ix_question_options_question_id', 'question_options', ['question_id'], unique=False)
    op.create_table('trivia_questions',
    sa.Column('trivia_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_trivia_questions_question_id_questions')),
    sa.ForeignKeyConstraint(['trivia_id'], ['trivias.id'], name=op.f('fk_trivia_questions_trivia_id_trivias')),
    sa.PrimaryKeyConstraint('trivia_id', 'question_id', name=op.f('pk_trivia_questions'))
    )
    op.create_index('ix_trivia_questions_question_id', 'trivia_questions', ['question_id'], unique=False)
    op.create_table('trivia_users',
    sa.Column('trivia_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trivia_id'], ['trivias.id'], name=op.f('fk_trivia_users_trivia_id_trivias')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trivia_users_user_id_users')),
    sa.PrimaryKeyConstraint('trivia_id', 'user_id', name=op.f('pk_trivia_users'))
    )
    op.create_index('ix_trivia_users_user_id', 'trivia_users', ['user_id'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('participation_id', sa.Uuid(), nullable=False),
    sa.Column('trivia_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('option_id', sa.Uuid(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('score_awarded', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['question_options.id'], name=op.f('fk_answers_option_id_question_options')),
    sa.ForeignKeyConstraint(['participation_id'], ['participations.id'], name=op.f('fk_answers_participation_id_participations')),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_answers_question_id_questions')),
    sa.ForeignKeyConstraint(['trivia_id', 'question_id'], ['trivia_questions.trivia_id', 'trivia_questions.question_id'], name='fk_answers_trivia_question'),
    sa.ForeignKeyConstraint(['trivia_id'], ['trivias.id'], name=op.f('fk_answers_trivia_id_trivias')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answers')),
    sa.UniqueConstraint('participation_id', 'question_id', name='uq_answer_participation_question')
    )
    op.create_index('ix_answers_option_id', 'answers', ['option_id'], unique=False)
    op.create_index('ix_answers_participation_id', 'answers', ['participation_id'], unique=False)
    op.create_index('ix_answers_trivia_question', 'answers', ['trivia_id', 'question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_answers_trivia_question', table_name='answers')
    op.drop_index('ix_answers_participation_id', table_name='answers')
    op.drop_index('ix_answers_option_id', table_name='answers')
    op.drop_table('answers')
    op.drop_index('ix_trivia_users_user_id', table_name='trivia_users')
    op.drop_table('trivia_users')
    op.drop_index('ix_trivia_questions_question_id', table_name='trivia_questions')
    op.drop_table('trivia_questions')
    op.drop_index('ix_question_options_question_id', table_name='question_options')
    op.drop_table('question_options')
    op.drop_index('ix_participations_user_id', table_name='participations')
    op.drop_index('ix_participations_trivia_id', table_name='participations')
    op.drop_table('participations')
    op.drop_table('users')
    op.drop_table('trivias')
    op.drop_table('questions')
    # ### end Alembic commands ###
